### PR TITLE
Use arduino CLI & support for anonymous code

### PR DESCRIPTION
**Pull request by pravdomil**
From version 1.5.0 arduino has its own official CLI, following tool is unofficial but still on development
https://github.com/arduino/Arduino/blob/ide-1.5.x/build/shared/manpage.adoc

### CODE REVIEW

**Comment by dctrotz** [comment]
:+1:

**Comment by nasser** [comment]
Oh this is excellent. We should make the switch. I will get on it as soon as I can, but anyone is welcome to take a shot at it in the meantime!

**Comment by Pravdomil** [comment]
done

**Comment by nasser** [comment]
Excellent!

**Pull request merged**
